APPLICATION_STATUS_PROCESSING = "PROCESSING"
APPLICATION_STATUS_PROCESSED = "PROCESSED"
APPLICATION_STATUS_FAILED = "FAILED"
APPLICATION_STATUS_READY = "READY"
APPLICATION_STATUS_ASSIGNED = "ASSIGNED"
APPLICATION_STATUS_COMPLETE = "COMPLETE"

APPLICATION_STATUSES_ACTIVE_ASSIGNMENT = {APPLICATION_STATUS_ASSIGNED}
APPLICATION_STATUSES_ASSIGNABLE = {APPLICATION_STATUS_READY, APPLICATION_STATUS_ASSIGNED}
APPLICATION_STATUSES_QUEUE_REMOVABLE = {APPLICATION_STATUS_PROCESSING, APPLICATION_STATUS_FAILED}

PROCESSING_JOB_STATUS_QUEUED = "queued"
PROCESSING_JOB_STATUS_RUNNING = "running"
PROCESSING_JOB_STATUS_COMPLETED = "completed"
PROCESSING_JOB_STATUS_FAILED = "failed"

WORKSPACE_STATUS_DRAFT = "draft"
WORKSPACE_STATUS_LAUNCHED = "launched"
WORKSPACE_STATUS_POSTGAME = "postgame"
WORKSPACE_STATUS_COMPLETED = "completed"
WORKSPACE_STATUS_VALUES = {
    WORKSPACE_STATUS_DRAFT,
    WORKSPACE_STATUS_LAUNCHED,
    WORKSPACE_STATUS_POSTGAME,
    WORKSPACE_STATUS_COMPLETED,
}

QUESTION_STATUS_UNASKED = "unasked"
QUESTION_STATUS_SATISFACTORY = "satisfactory"
QUESTION_STATUS_MIXED = "mixed"
QUESTION_STATUS_UNSATISFACTORY = "unsatisfactory"
QUESTION_STATUS_VALUES = {
    QUESTION_STATUS_UNASKED,
    QUESTION_STATUS_SATISFACTORY,
    QUESTION_STATUS_MIXED,
    QUESTION_STATUS_UNSATISFACTORY,
}

USER_ACCESS_STATUS_INVITED = "invited"
USER_ACCESS_STATUS_ACTIVE = "active"
USER_ACCESS_STATUS_DEACTIVATED = "deactivated"
USER_ACCESS_STATUS_VALUES = {
    USER_ACCESS_STATUS_INVITED,
    USER_ACCESS_STATUS_ACTIVE,
    USER_ACCESS_STATUS_DEACTIVATED,
}
